export const SCHEMA_SQL = `
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE TABLE IF NOT EXISTS public.site_content (id text NOT NULL, content jsonb NOT NULL, updated_at timestamptz NOT NULL DEFAULT now(), CONSTRAINT site_content_pkey PRIMARY KEY (id));
CREATE TABLE IF NOT EXISTS public.collections (id text NOT NULL, name text NOT NULL, description text NOT NULL, image_url text NOT NULL, item_count_label text NOT NULL, sort_order integer NOT NULL DEFAULT 0, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), CONSTRAINT collections_pkey PRIMARY KEY (id));
CREATE TABLE IF NOT EXISTS public.products (id text NOT NULL, name text NOT NULL, price numeric NOT NULL CHECK (price >= 0), main_image_url text NOT NULL, gallery_image_urls text[] NOT NULL DEFAULT '{}', category_label text, description text NOT NULL, details text[] NOT NULL DEFAULT '{}', sizes text[] NOT NULL DEFAULT '{}', section text NOT NULL DEFAULT 'general' CHECK (section = ANY (ARRAY['general','new_arrivals','best_sellers'])), collection_ids text[] NOT NULL DEFAULT '{}', sort_order integer NOT NULL DEFAULT 0, is_active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), CONSTRAINT products_pkey PRIMARY KEY (id));
CREATE TABLE IF NOT EXISTS public.app_users (id uuid NOT NULL DEFAULT gen_random_uuid(), email text NOT NULL UNIQUE, first_name text NOT NULL, last_name text NOT NULL, phone text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), CONSTRAINT app_users_pkey PRIMARY KEY (id));
CREATE TABLE IF NOT EXISTS public.saved_addresses (id uuid NOT NULL DEFAULT gen_random_uuid(), user_id uuid NOT NULL, label text NOT NULL, first_name text NOT NULL, last_name text NOT NULL, phone text NOT NULL, address text NOT NULL, apartment text, city text NOT NULL, state text NOT NULL, zip_code text NOT NULL, country text NOT NULL DEFAULT 'India', is_default boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), CONSTRAINT saved_addresses_pkey PRIMARY KEY (id), CONSTRAINT saved_addresses_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_users(id));
CREATE TABLE IF NOT EXISTS public.order_policies (id boolean NOT NULL DEFAULT true CHECK (id = true), shipping_amount numeric NOT NULL DEFAULT 15 CHECK (shipping_amount >= 0), free_shipping_threshold numeric NOT NULL DEFAULT 200 CHECK (free_shipping_threshold >= 0), tax_rate numeric NOT NULL DEFAULT 8 CHECK (tax_rate >= 0), automatic_shipping_enabled boolean NOT NULL DEFAULT false, shippo_from_name text NOT NULL DEFAULT '', shippo_from_company text NOT NULL DEFAULT '', shippo_from_street1 text NOT NULL DEFAULT '', shippo_from_street2 text NOT NULL DEFAULT '', shippo_from_city text NOT NULL DEFAULT '', shippo_from_state text NOT NULL DEFAULT '', shippo_from_zip text NOT NULL DEFAULT '', shippo_from_country text NOT NULL DEFAULT 'IN', shippo_from_phone text NOT NULL DEFAULT '', shippo_from_email text NOT NULL DEFAULT '', shippo_from_is_residential boolean NOT NULL DEFAULT false, shippo_parcel_length numeric NOT NULL DEFAULT 10 CHECK (shippo_parcel_length > 0), shippo_parcel_width numeric NOT NULL DEFAULT 10 CHECK (shippo_parcel_width > 0), shippo_parcel_height numeric NOT NULL DEFAULT 4 CHECK (shippo_parcel_height > 0), shippo_parcel_weight numeric NOT NULL DEFAULT 1 CHECK (shippo_parcel_weight > 0), shippo_parcel_distance_unit text NOT NULL DEFAULT 'in' CHECK (shippo_parcel_distance_unit = ANY (ARRAY['in','cm'])), shippo_parcel_mass_unit text NOT NULL DEFAULT 'lb' CHECK (shippo_parcel_mass_unit = ANY (ARRAY['lb','oz','g','kg'])), shippo_label_file_type text NOT NULL DEFAULT 'PDF_4x6' CHECK (shippo_label_file_type = ANY (ARRAY['PNG','PNG_2.3x7.5','PDF','PDF_2.3x7.5','PDF_4x6','PDF_4x8','PDF_A4','PDF_A5','PDF_A6','ZPLII'])), active_theme_name text DEFAULT 'default', updated_at timestamptz NOT NULL DEFAULT now(), show_ticker boolean NOT NULL DEFAULT true, section_styles jsonb NOT NULL DEFAULT '{"homeHero":"video"}', CONSTRAINT order_policies_pkey PRIMARY KEY (id));
CREATE TABLE IF NOT EXISTS public.coupons (code text NOT NULL, label text NOT NULL, coupon_type text NOT NULL CHECK (coupon_type = ANY (ARRAY['universal','one_time'])), discount_type text NOT NULL CHECK (discount_type = ANY (ARRAY['percent','amount'])), discount_value numeric NOT NULL CHECK (discount_value >= 0), active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), CONSTRAINT coupons_pkey PRIMARY KEY (code));
CREATE TABLE IF NOT EXISTS public.orders (id text NOT NULL, user_id uuid, user_email text NOT NULL, status text NOT NULL DEFAULT 'placed' CHECK (status = ANY (ARRAY['placed','packed','in_transit','delivered'])), payment_method text NOT NULL CHECK (payment_method = ANY (ARRAY['cod','razorpay'])), payment_verified boolean NOT NULL DEFAULT false, razorpay_payment_id text, coupon_code text, shipping_address jsonb NOT NULL, totals jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), CONSTRAINT orders_pkey PRIMARY KEY (id), CONSTRAINT orders_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_users(id), CONSTRAINT orders_coupon_code_fkey FOREIGN KEY (coupon_code) REFERENCES public.coupons(code));
CREATE TABLE IF NOT EXISTS public.order_items (id uuid NOT NULL DEFAULT gen_random_uuid(), order_id text NOT NULL, product_id text, product_name text NOT NULL, product_image text, size text NOT NULL, quantity integer NOT NULL CHECK (quantity > 0), unit_price numeric NOT NULL CHECK (unit_price >= 0), line_total numeric NOT NULL CHECK (line_total >= 0), created_at timestamptz NOT NULL DEFAULT now(), CONSTRAINT order_items_pkey PRIMARY KEY (id), CONSTRAINT order_items_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id), CONSTRAINT order_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id));
CREATE TABLE IF NOT EXISTS public.themes (id uuid NOT NULL DEFAULT gen_random_uuid(), name text NOT NULL UNIQUE, label text NOT NULL, colors jsonb NOT NULL, is_active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), CONSTRAINT themes_pkey PRIMARY KEY (id));
`;
export const SEED_SQL = `
INSERT INTO public.collections (id, name, description, image_url, item_count_label, sort_order) VALUES ('contemporary','Contemporary Collection','Modern cuts and innovative styling for the forward-thinking gentleman.','/thudarum-sky-blue-blazer.jpg','10 items',30),('evening','Evening Collection','Luxurious velvet and satin pieces designed to make a statement at formal occasions.','/thudarum-navy-velvet-blazer.jpg','6 items',40),('executive','Executive Collection','Bold, sophisticated pieces for the modern power dresser.','/thudarum-burgundy-evening-suit.jpg','12 items',10),('heritage','Heritage Collection','Classic tailoring with timeless appeal.','/thudarum-green-check-blazer.jpg','8 items',20) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.products (id,name,price,main_image_url,gallery_image_urls,category_label,description,details,sizes,section,collection_ids,sort_order,is_active) VALUES ('classic-taupe-double-breasted-suit','Classic Taupe Double-Breasted Suit',1289.00,'/thudarum-taupe-suit-hero.jpg',ARRAY['/thudarum-taupe-suit-detail.jpg'],'Suits','An impeccably tailored double-breasted suit in refined taupe wool.',ARRAY['100% Italian wool','Double-breasted closure'],ARRAY['38','40','42','44'],'new_arrivals',ARRAY['executive','contemporary'],10,true),('navy-velvet-double-breasted-jacket','Navy Velvet Double-Breasted Jacket',1195.00,'/thudarum-navy-velvet-blazer.jpg',ARRAY['/thudarum-navy-velvet-detail.jpg'],'Blazers','A luxurious navy velvet jacket with elevated texture.',ARRAY['Italian cotton velvet','Evening-ready finish'],ARRAY['38','40','42','44'],'best_sellers',ARRAY['evening'],20,true) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.coupons (code,label,coupon_type,discount_type,discount_value,active) VALUES ('WELCOME10','Welcome 10%','universal','percent',10.00,true) ON CONFLICT (code) DO NOTHING;
INSERT INTO public.order_policies (id, shipping_amount, free_shipping_threshold, tax_rate, active_theme_name, show_ticker, section_styles) VALUES (true,15.00,200.00,8.00,'default',true,'{"homeHero":"video"}') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.themes (name,label,colors,is_active) VALUES ('default','Minimalist White','{"background":"oklch(0.985 0 0)","foreground":"oklch(0.145 0 0)","primary":"oklch(0.205 0 0)"}',true),('golden','Light Golden','{"background":"oklch(0.98 0.01 70)","foreground":"oklch(0.25 0.08 50)","primary":"oklch(0.70 0.18 62)"}',true),('midnight','Midnight Dark','{"background":"oklch(0.15 0.02 240)","foreground":"oklch(0.98 0.01 240)","primary":"oklch(0.6 0.15 250)"}',true) ON CONFLICT (name) DO NOTHING;
INSERT INTO public.site_content (id,content) VALUES ('site','{"brandName":"FABRICA","tickerMessages":["FREE SHIPPING ON ORDERS OVER ₹200","30-DAY RETURNS","HOST YOUR OWN STORE IN MINUTES"]}'),('home','{"heroTitle":"Launch Your Store","heroSubtitle":"Discover powerful tools crafted for the modern merchant","bestSellersTitle":"Best Sellers","collectionsTitle":"Collections","newArrivalsTitle":"New Arrivals"}') ON CONFLICT (id) DO NOTHING;
`;
export const STORAGE_POLICIES_SQL = `
INSERT INTO storage.buckets (id, name, public) VALUES ('pic', 'pic', true) ON CONFLICT (id) DO NOTHING;
DO $$ BEGIN CREATE POLICY "pic_select_all" ON storage.objects FOR SELECT USING (bucket_id = 'pic'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "pic_insert_all" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'pic'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "pic_update_all" ON storage.objects FOR UPDATE USING (bucket_id = 'pic'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "pic_delete_all" ON storage.objects FOR DELETE USING (bucket_id = 'pic'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
`;
export const FULL_SQL = `${SCHEMA_SQL}\n${SEED_SQL}\n${STORAGE_POLICIES_SQL}`;
